title: HumanLearning-ML!
subtitle: ML Blog
email: rati.kapoor27@gmail.com

baseurl: ""
github_username:  ratikapoor

use_math: true

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

# Build settings
highlighter: rouge
markdown: kramdown

gems:
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-feed

kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["node_modules"]

theme: jekyll-theme-clean-blog

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  
analytics :
  provider : google
  google:
    tracking_id : 'UA-164494745-1'
  getclicky :
    site_id
