# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# title: HumanLearning-ML!
# description: Training human brains to understand machine learning ❤
# github_username: ratikapoor
name: HumanLearning-ML!
title: nil
# Email and twitter are optional:
email: rati.kapoor27@gmail.com
twitter_username:

# Set this to true to get LaTeX math equation support
use_math: True
header_pages:
  - about.md

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
#   title: nil

# Build settings
highlighter: rouge
markdown: kramdown

gems:
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-feed

kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["node_modules"]

theme: jekyll-theme-clean-blog

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  
analytics :
  provider : google
  google:
    tracking_id : 'UA-164494745-1'
  getclicky :
    site_id
