# Site settings
title: Dig Deep
subtitle: Machine Learning Blog
email: abhijeetbiswas2212.ab@gmail.com
description: "A blog where we dig deep into the Math and Code behind Machine learning Algorithms"
baseurl: ""
url: "https://ab2212.github.io"
twitter_username: AbhiB2212
github_username:  AB2212

use_math: true

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

# Build settings
highlighter: rouge
markdown: kramdown

gems:
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-feed

kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["node_modules"]

theme: jekyll-theme-clean-blog

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  
analytics :
  provider : google
  google:
    tracking_id : 'UA-164494745-1'
  getclicky :
    site_id
